-- 创建产品表
CREATE TABLE IF NOT EXISTS t_product (
    product_id VARCHAR(36) NOT NULL COMMENT '产品ID',
    product_code VARCHAR(50) NOT NULL COMMENT '产品代码',
    product_name VARCHAR(100) NOT NULL COMMENT '产品名称',
    product_desc TEXT COMMENT '产品描述',
    form VARCHAR(20) NOT NULL COMMENT '产品形态（团险/个险）',
    insurance_type VARCHAR(20) NOT NULL COMMENT '险种类型',
    category VARCHAR(20) NOT NULL COMMENT '产品类别（MAIN-主险/RIDER-附加险）',
    version VARCHAR(10) NOT NULL COMMENT '产品版本',
    status VARCHAR(20) NOT NULL COMMENT '产品状态',
    original_product_id VARCHAR(36) COMMENT '原始产品ID',
    effective_time DATETIME COMMENT '生效时间',
    invalid_time DATETIME COMMENT '失效时间',
    sale_start_time DATETIME COMMENT '销售开始时间',
    sale_end_time DATETIME COMMENT '销售结束时间',
    insure_condition JSON COMMENT '投保条件',
    coverage_period JSON COMMENT '保障期间配置',
    payment_config JSON COMMENT '缴费方式配置',
    pricing_basic_rule JSON COMMENT '定价基础规则',
    issuance_process_config JSON COMMENT '出单流程配置',
    policy_form_config JSON COMMENT '保单形态配置',
    underwriting_config JSON COMMENT '核保配置',
    sales_channels JSON COMMENT '销售渠道配置',
    attach_product_ids JSON COMMENT '附加险产品ID列表',
    auditor_id VARCHAR(50) COMMENT '审核人ID',
    auditor_name VARCHAR(50) COMMENT '审核人姓名',
    audit_opinion VARCHAR(500) COMMENT '审核意见',
    audit_time DATETIME COMMENT '审核时间',
    audit_result VARCHAR(20) COMMENT '审核结果',
    pricing_rule_set_id VARCHAR(50) COMMENT '定价规则集ID',
    insure_condition_rule_set_id VARCHAR(50) COMMENT '投保条件规则集ID',
    underwriting_rule_set_id VARCHAR(50) COMMENT '核保规则集ID',
    tenant_id VARCHAR(36) NOT NULL COMMENT '租户ID',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    created_by VARCHAR(50) NOT NULL COMMENT '创建人',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    updated_by VARCHAR(50) NOT NULL COMMENT '更新人',
    PRIMARY KEY (product_id),
    UNIQUE KEY uk_product_code_tenant (product_code, tenant_id),
    INDEX idx_product_tenant_id (tenant_id),
    INDEX idx_product_status (status),
    INDEX idx_product_insurance_type (insurance_type),
    INDEX idx_product_original_id (original_product_id),
    INDEX idx_product_type_status (insurance_type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='保险产品表';

-- 创建产品条款关联表
CREATE TABLE IF NOT EXISTS t_product_clause_rel (
    id BIGINT AUTO_INCREMENT COMMENT '主键ID',
    product_id VARCHAR(36) NOT NULL COMMENT '产品ID',
    clause_id VARCHAR(36) NOT NULL COMMENT '条款ID',
    clause_version VARCHAR(10) NOT NULL COMMENT '条款版本',
    is_main_clause BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否主条款',
    tenant_id VARCHAR(36) NOT NULL COMMENT '租户ID',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    created_by VARCHAR(50) NOT NULL COMMENT '创建人',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    updated_by VARCHAR(50) NOT NULL COMMENT '更新人',
    PRIMARY KEY (id),
    INDEX idx_product_clause_rel_product_id (product_id),
    INDEX idx_product_clause_rel_clause_id (clause_id),
    INDEX idx_product_clause_rel_tenant_id (tenant_id),
    FOREIGN KEY (product_id) REFERENCES t_product(product_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产品条款关联表';

-- 创建产品销售渠道关联表
CREATE TABLE IF NOT EXISTS t_product_sales_channel (
    id BIGINT AUTO_INCREMENT COMMENT '主键ID',
    product_id VARCHAR(36) NOT NULL COMMENT '产品ID',
    channel_code VARCHAR(50) NOT NULL COMMENT '渠道代码',
    channel_name VARCHAR(100) NOT NULL COMMENT '渠道名称',
    start_time DATETIME COMMENT '生效时间',
    end_time DATETIME COMMENT '失效时间',
    tenant_id VARCHAR(36) NOT NULL COMMENT '租户ID',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    created_by VARCHAR(50) NOT NULL COMMENT '创建人',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    updated_by VARCHAR(50) NOT NULL COMMENT '更新人',
    PRIMARY KEY (id),
    INDEX idx_product_sales_channel_product_id (product_id),
    INDEX idx_product_sales_channel_tenant_id (tenant_id),
    FOREIGN KEY (product_id) REFERENCES t_product(product_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产品销售渠道关联表';

-- 创建产品附加险关联表
CREATE TABLE IF NOT EXISTS t_product_attach_rel (
    id BIGINT AUTO_INCREMENT COMMENT '主键ID',
    main_product_id VARCHAR(36) NOT NULL COMMENT '主险产品ID',
    attach_product_id VARCHAR(36) NOT NULL COMMENT '附加险产品ID',
    tenant_id VARCHAR(36) NOT NULL COMMENT '租户ID',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    created_by VARCHAR(50) NOT NULL COMMENT '创建人',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    updated_by VARCHAR(50) NOT NULL COMMENT '更新人',
    PRIMARY KEY (id),
    INDEX idx_product_attach_rel_main_product_id (main_product_id),
    INDEX idx_product_attach_rel_attach_product_id (attach_product_id),
    INDEX idx_product_attach_rel_tenant_id (tenant_id),
    FOREIGN KEY (main_product_id) REFERENCES t_product(product_id) ON DELETE CASCADE,
    FOREIGN KEY (attach_product_id) REFERENCES t_product(product_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产品附加险关联表';

-- 创建产品模板表
CREATE TABLE IF NOT EXISTS t_product_template (
    template_id VARCHAR(36) NOT NULL COMMENT '模板ID',
    template_code VARCHAR(50) NOT NULL COMMENT '模板代码',
    template_name VARCHAR(100) NOT NULL COMMENT '模板名称',
    insurance_type VARCHAR(20) NOT NULL COMMENT '险种类型',
    form VARCHAR(20) NOT NULL COMMENT '产品形态',
    category VARCHAR(20) NOT NULL COMMENT '产品类别',
    status VARCHAR(20) NOT NULL COMMENT '模板状态',
    description TEXT COMMENT '模板描述',
    base_config JSON COMMENT '基础配置',
    tenant_id VARCHAR(36) NOT NULL COMMENT '租户ID',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    created_by VARCHAR(50) NOT NULL COMMENT '创建人',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    updated_by VARCHAR(50) NOT NULL COMMENT '更新人',
    PRIMARY KEY (template_id),
    UNIQUE KEY uk_template_code_tenant (template_code, tenant_id),
    INDEX idx_product_template_tenant_id (tenant_id),
    INDEX idx_product_template_insurance_type (insurance_type),
    INDEX idx_product_template_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产品模板表';
